force-app/main/default/objects/Access__c/Access__c.object-meta.xml
<CustomObject>
    <label>Access</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Access__c/fields/Access_Expire_Date__c.field-meta.xml
<CustomField>
    <fullName>Access_Expire_Date__c</fullName>
    <label>Access Expire Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Access__c/fields/Access_Expire_Time__c.field-meta.xml
<CustomField>
    <fullName>Access_Expire_Time__c</fullName>
    <label>Access Expire Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Access__c/fields/Permission_to_Update__c.field-meta.xml
<CustomField>
    <fullName>Permission_to_Update__c</fullName>
    <label>Permission to Update</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Request_For_Permission_Set__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Buyer Manager</fullName>
            </value>
            <value>
                <fullName>C360 High Scale Flow Integration User</fullName>
            </value>
            <value>
                <fullName>Commerce Admin</fullName>
            </value>
            <value>
                <fullName>Contact Center Admin</fullName>
            </value>
            <value>
                <fullName>Contact Center Agent</fullName>
            </value>
            <value>
                <fullName>Contact Center Supervisor</fullName>
            </value>
            <value>
                <fullName>CRM User</fullName>
            </value>
            <value>
                <fullName>Experience Profile Manager</fullName>
            </value>
            <value>
                <fullName>Facility Manager</fullName>
            </value>
            <value>
                <fullName>FieldServiceMobile StandardPermSet</fullName>
            </value>
            <value>
                <fullName>Merchandiser</fullName>
            </value>
            <value>
                <fullName>Order Management Agent</fullName>
            </value>
            <value>
                <fullName>Order Management Operations Manager</fullName>
            </value>
            <value>
                <fullName>Order Management Shopper</fullName>
            </value>
            <value>
                <fullName>Order Management Store Associate</fullName>
            </value>
            <value>
                <fullName>Queue Manager</fullName>
            </value>
            <value>
                <fullName>Sales Cloud User</fullName>
            </value>
            <value>
                <fullName>Sales Engagement Basic User</fullName>
            </value>
            <value>
                <fullName>Salesforce Apex Guru</fullName>
            </value>
            <value>
                <fullName>Salesforce CMS Integration Admin</fullName>
            </value>
            <value>
                <fullName>Salesforce Console User</fullName>
            </value>
            <value>
                <fullName>SCRT2 Integration User</fullName>
            </value>
            <value>
                <fullName>Seas Indexing C2C User Perm</fullName>
            </value>
            <value>
                <fullName>Security Center Integration User</fullName>
            </value>
            <value>
                <fullName>Service Cloud User</fullName>
            </value>
            <value>
                <fullName>Shopper</fullName>
            </value>
            <value>
                <fullName>Slack Service User</fullName>
            </value>
            <value>
                <fullName>Standard Einstein Activity Capture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Access__c/fields/Profile_to_Update__c.field-meta.xml
<CustomField>
    <fullName>Profile_to_Update__c</fullName>
    <label>Profile to Update</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Request_For_Profile__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contract Manager</fullName>
            </value>
            <value>
                <fullName>Custom: Marketing Profile</fullName>
            </value>
            <value>
                <fullName>Custom: Sales Profile</fullName>
            </value>
            <value>
                <fullName>Custom: Support Profile</fullName>
            </value>
            <value>
                <fullName>Custom Standard Admin</fullName>
            </value>
            <value>
                <fullName>Marketing User</fullName>
            </value>
            <value>
                <fullName>Minimum Access - Salesforce</fullName>
            </value>
            <value>
                <fullName>Read Only</fullName>
            </value>
            <value>
                <fullName>Solution Manager</fullName>
            </value>
            <value>
                <fullName>Standard User</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Access__c/fields/Request_For_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Request_For_Permission_Set__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request For Permission Set</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Access__c/fields/Request_For_Profile__c.field-meta.xml
<CustomField>
    <fullName>Request_For_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Request For Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Access__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RequestForAccess.cls
/*
 Name: RequestForAccess
 Description: Get the Request and upgrade the access and schedule apex for revoke the access
 Created By : Cloud Avengers
 Date       : 9-Dec-2023
*/

@SuppressWarnings('PMD.AvoidGlobalModifier, PMD.ApexCRUDViolation')

global with sharing class RequestForAccess{
    
    public static void accessTriggerController(List<Access__c> access)
    {
           for(Access__c obj : access)
           {
               if (Obj.Status__c == 'Approved') 
                {  
                    String recordId=obj.Id;
                    RequestForAccess.upgradeAccess(recordId);
                }
           }
    }
 
    public static Access__c getAccessDetails(String currentRecordId){
    Access__c access = [SELECT Id, Name, Profile_to_Update__c, Permission_to_Update__c, Request_For_Profile__c, Request_For_Permission_Set__c,
                        Access_Expire_Date__c,Access_Expire_Time__c,Email__c,Phone_Number__c
                        FROM Access__c
                        WHERE Id =: currentRecordId
                        WITH USER_MODE ];
    return access;
    }
    @future
    global static void upgradeAccess(String recordId){
        
        Access__c access = RequestForAccess.getAccessDetails(recordId);
        
        Profile profiles;
        String requesterOriginalProfileId;
        String permissionSetId;
        String currentRecordId = recordId;
        List<PermissionSet> permissionSets = new List<PermissionSet>{};
        
        String schedulejobName = access.Name; 
        String profileToBeUpdate = access.Profile_to_Update__c;
        String permissionSetToBeUpdate = access.Permission_to_Update__c;
        Boolean profileCheck = access.Request_For_Profile__c;
        Boolean permissionCheck = access.Request_For_Permission_Set__c;
        Date estimatedDate = access.Access_Expire_Date__c; 
        Time estimatedTime = access.Access_Expire_Time__c; 
      
        Integer hour = EstimatedTime.hour();
        Integer min = EstimatedTime.minute();
        Datetime scheduledTime = Datetime.newInstanceGmt(EstimatedDate.year(), EstimatedDate.month(), EstimatedDate.day(), 0, 0, 0);
        
        String cronExpression = 0 + ' ' + min + ' ' + hour + ' ' + ScheduledTime.day() + ' ' + ScheduledTime.month() + ' ? ' + ScheduledTime.year();
        String userId = UserInfo.getUserId();
        
        String requesterUserId = [SELECT Id, ProcessInstance.SubmittedBy.Id 
                                  FROM ProcessInstanceStep
                                  WHERE StepStatus = 'Approved' AND ActorId =:userId 
                                  ORDER BY CreatedDate DESC LIMIT 1].ProcessInstance.SubmittedBy.Id;
        User requestedUser = [SELECT Id, firstname, lastname, IsActive, ProfileId, UserType 
                              FROM User 
                              WHERE Id = :requesterUserId
                              WITH USER_MODE];
        
        if(permissionCheck){
           permissionSets = [SELECT Id 
                             FROM PermissionSet 
                             WHERE Label = :  permissionSetToBeUpdate 
                             WITH USER_MODE LIMIT 1];
           if (!permissionSets.isEmpty()) {
                permissionSetId = permissionSets[0].Id;
                try {
                    PermissionSetAssignment newAssignment = new PermissionSetAssignment( 
                                            AssigneeId = RequesterUserId,
                                            PermissionSetId = permissionSetId
                    );
                    INSERT newAssignment;
                }catch (Exception e) {
                    System.debug('Error Message: ' + e.getMessage());
                    throw e;
                }
            } 
        }
        if(ProfileCheck){
            RequesterOriginalProfileId = requestedUser.ProfileId;
            profiles = [SELECT Id, Name FROM profile WHERE Name =: ProfileToBeUpdate WITH USER_MODE];
            requestedUser.ProfileId = profiles.Id;
            try{
                UPDATE requestedUser; 
            } catch(Exception e){
              System.debug('Error Message: '+ e.getMessage());
            }
        }

        AccessSchedularClass scheduledJob = new AccessSchedularClass(RequesterUserId, RequesterOriginalProfileId, permissionSetId);
        System.schedule( SchedulejobName, cronExpression , scheduledJob);
    }
    
     global static void revoketheProfileAccess(String requesterUserId, String requesterOriginalProfileId){
         
         User requestedUser = [SELECT Id, firstname, lastname, email,  IsActive, ProfileId, UserType 
                               FROM User  
                               WHERE Id = :RequesterUserId
                               WITH USER_MODE];
         
         Profile oldProfile = [SELECT Id, Name 
                               FROM profile 
                               WHERE id=: RequesterOriginalProfileId
                               WITH USER_MODE];

         requestedUser.ProfileId = OldProfile.Id;
         
         UPDATE requestedUser;
     } 
    
    global static void revokethePermissionsetAccess(String requesterId, String requesterPermissionSetId){ 

        PermissionSetAssignment existingAssignment = [
            SELECT Id
            FROM PermissionSetAssignment
            WHERE AssigneeId = : RequesterId
            AND PermissionSetId = : RequesterPermissionSetId
            WITH USER_MODE
            LIMIT 1
        ];
        
        if (existingAssignment != null) 
        {
            DELETE existingAssignment;
        }else{
            System.debug('Permission Set is not Assigned to the User');
        }
    } 
}